### ISSUE TITLE
Doesn't work when activated from parent item

### ISSUE THREAD

**Issue by paultjevdh** [retorquere/zotero-open-pdf#4]
Hi,
I just discovered the existence of this addon on the zotero forum. Thanks for your work.

However, for me it only works when I select 'open in external viewer' from the pdf. 
On the parent item, the option is also present and 'active'  (not greyed out), but it does nothing. 
The zotero internal pdf options 'opebnn pdf'  and 'open pdf in new window'  work in both cases.
It would be great if you could fix that.

Best regards,
PAul

**Comment by qqobb** [comment]
@paultjevdh: The issue you describe should be fixed in the [latest release](https://github.com/retorquere/zotero-open-pdf/releases/latest). I guess you might have tried an earlier release, since it's currently being referred to in [this discussion](https://forums.zotero.org/discussion/comment/410796/#Comment_410796).

@retorquere: Perhaps you could edit that posting, so other users will not mistakenly install an old version.

**Comment by paultjevdh** [comment]
Hi,
That's weird. It works now, but didn't last week. I used zotero 6.0.13 and zotero-open-pdf 0.0.4, which are still the latest today.
All I can say for now is that I don't know the exact conditions required to produce the error.
Paul

**Comment by qqobb** [comment]
Most likely you initially installed v0.0.2 which had that issue and was linked to in the forums. You then received an auto-update to v0.0.4 and the issue is gone now.

I guess the issue can be closed for now.

**Comment by paultjevdh** [comment]
Hi,
You're correct. I found the installer, it was 0.0.2
